apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: accountingweb-container
        image: fs.panga-ghost.ts.net:5443/accountingweb:v3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DB_ENGINE
            value: "django.db.backends.mysql"
          - name: DB_NAME
            value: "accounting_db"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-host
          - name: DB_PORT
            value: "3306"
          - name: SECRET_KEY
            value: "django-insecure-7y1x"
          - name: DEBUG
            value: "True"