# Generated by Django 5.0.3 on 2024-08-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.CharField(max_length=50),
        ),
    ]
