# Generated by Django 5.0.3 on 2024-08-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingWeb', '0002_alter_transaction_credit_alter_transaction_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.CharField(choices=[('Accounts Payable', 'Accounts Payable'), ('Accounts Receivable', 'Accounts Receivable'), ('Buildings', 'Buildings'), ('Cash', 'Cash'), ('Checking Accounts', 'Checking Accounts'), ('Credit Cards Payable', 'Credit Cards Payable'), ('Entertainment Expenses', 'Entertainment Expenses'), ('Food Expenses', 'Food Expenses'), ('Furniture & Fixtures', 'Furniture & Fixtures'), ('General Equity Account', 'General Equity Account'), ('Insurance Expense', 'Insurance Expense'), ('Interest Expense', 'Interest Expense'), ('Interest Payable', 'Interest Payable'), ('Inventory', 'Inventory'), ('Investments Assets', 'Investments Assets'), ('Investments Money', 'Investments Money'), ('Land', 'Land'), ('Lodge Expenses', 'Lodge Expenses'), ('Mortgage Payable', 'Mortgage Payable'), ('Notes Payable', 'Notes Payable'), ('Office Supplies', 'Office Supplies'), ('Office Supplies Expense', 'Office Supplies Expense'), ('Prepaid Expenses', 'Prepaid Expenses'), ('Rent Expense', 'Rent Expense'), ('Revenue-Gift', 'Revenue-Gift'), ('Revenue-Investment', 'Revenue-Investment'), ('Revenue-Salary', 'Revenue-Salary'), ('Revenue-Tutoring', 'Revenue-Tutoring'), ('Savings Accounts', 'Savings Accounts'), ('Telephone Expense', 'Telephone Expense'), ('Utilities Expenses', 'Utilities Expenses'), ('Vehicles', 'Vehicles'), ('Wages Payable', 'Wages Payable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.CharField(choices=[('Accounts Payable', 'Accounts Payable'), ('Accounts Receivable', 'Accounts Receivable'), ('Buildings', 'Buildings'), ('Cash', 'Cash'), ('Checking Accounts', 'Checking Accounts'), ('Credit Cards Payable', 'Credit Cards Payable'), ('Entertainment Expenses', 'Entertainment Expenses'), ('Food Expenses', 'Food Expenses'), ('Furniture & Fixtures', 'Furniture & Fixtures'), ('General Equity Account', 'General Equity Account'), ('Insurance Expense', 'Insurance Expense'), ('Interest Expense', 'Interest Expense'), ('Interest Payable', 'Interest Payable'), ('Inventory', 'Inventory'), ('Investments Assets', 'Investments Assets'), ('Investments Money', 'Investments Money'), ('Land', 'Land'), ('Lodge Expenses', 'Lodge Expenses'), ('Mortgage Payable', 'Mortgage Payable'), ('Notes Payable', 'Notes Payable'), ('Office Supplies', 'Office Supplies'), ('Office Supplies Expense', 'Office Supplies Expense'), ('Prepaid Expenses', 'Prepaid Expenses'), ('Rent Expense', 'Rent Expense'), ('Revenue-Gift', 'Revenue-Gift'), ('Revenue-Investment', 'Revenue-Investment'), ('Revenue-Salary', 'Revenue-Salary'), ('Revenue-Tutoring', 'Revenue-Tutoring'), ('Savings Accounts', 'Savings Accounts'), ('Telephone Expense', 'Telephone Expense'), ('Utilities Expenses', 'Utilities Expenses'), ('Vehicles', 'Vehicles'), ('Wages Payable', 'Wages Payable')], max_length=50),
        ),
    ]
