# Generated by Django 5.0.3 on 2025-06-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingWeb', '0003_alter_transaction_credit_alter_transaction_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.CharField(max_length=50),
        ),
    ]
