# Generated by Django 5.0.3 on 2025-10-06 01:40
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        # replace with your previous migration
        ('AccountingWeb', '0004_alter_transaction_credit_alter_transaction_debit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # EMPTY on purpose — the columns/indexes already exist in MySQL
            ],
            state_operations=[
                migrations.AddField(
                    model_name='account',
                    name='owner',
                    field=models.ForeignKey(
                        related_name='accounts',
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                        db_column='owner_id',
                    ),
                ),
                migrations.AddField(
                    model_name='transaction',
                    name='owner',
                    field=models.ForeignKey(
                        related_name='transactions',
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                        db_column='owner_id',
                    ),
                ),
            ],
        ),
    ]
