name: Build and Deploy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  prepare:
    name: Create Artifacts
    runs-on: [self-hosted, k3s]
    outputs:
      image_ref: ${{ steps.generate.outputs.image_ref }}

    steps:
      - name: Generate full image reference
        id: generate
        shell: bash
        run: |
          RAW_BRANCH="${GITHUB_REF##*/}"
          BRANCH=$(echo "$RAW_BRANCH" | tr '[:upper:]' '[:lower:]' \
                   | tr -c 'a-z0-9' '-' | sed 's/--*/-/g;s/^-//;s/-$//')
          DATE=$(date +%F-%H%M)
          IMAGE="${{ secrets.REGISTRY_URL }}/accountingweb:${DATE}--${BRANCH}"

          echo "image_ref=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "Generated image: $IMAGE"

      - name: Debug output
        run: |
          echo "Resolved image ref: ${{ steps.generate.outputs.image_ref }}"

  build:
    name: Build and Push Image
    runs-on: [self-hosted, k3s]
    needs: prepare

    steps:
      - uses: actions/checkout@v4

      # buildx (brings its own Docker)
      - id: buildx
        uses: docker/setup-buildx-action@v3

      # registry login (also brings Docker)
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # build & push image
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ needs.prepare.outputs.image_ref }}
          push: true
          builder: ${{ steps.buildx.outputs.name }}

  deploy:
    name: Deploy to k3s
    runs-on: [self-hosted, k3s]
    needs: [prepare, build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy image to cluster
        run: |
          IMAGE="${{ needs.prepare.outputs.image_ref }}"
          kubectl set image deployment/django-app \
                   accountingweb-container="$IMAGE"
          kubectl rollout status deployment/django-app
