name: Build and Push

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: [self-hosted, k3s]
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to private Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and push Docker image with date-based tag
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')
        DATE_TAG=$(date +%F-%H%M)
        IMAGE="${{ secrets.REGISTRY_URL }}/accountingweb:${BRANCH_NAME}-${DATE_TAG}"
        echo "Building and pushing image: $IMAGE"
        docker build -t $IMAGE .
        docker push $IMAGE
