name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, k3s-pod-runner]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to private Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
    - name: Build and tag Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build -t accountingweb:$TIMESTAMP .
    - name: Tag and push Docker image to registry
      run: |
        IMAGE=${{ secrets.REGISTRY_URL }}/accountingweb:latest
        docker tag accountingweb:$TIMESTAMP $IMAGE
        docker push $IMAGE
